name: "Test and Lint"
on: ["push", "pull_request"]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: twitcasting
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Build
        run: go build
      - name: Test
        run: go test ./...
      - name: Staticcheck
        run: staticcheck ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
